[package]
name = "hudhook-imgui-overlay-dx12"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "hudhook_imgui_overlay_dx12"
crate-type = ["cdylib"]

[dependencies]
hudhook = { workspace = true, features = ["dx12"] }
hudhook-imgui-overlay-ui = { path = "../overlay-ui" }
