[package]
name = "hudhook-imgui-overlay-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
electron-overlay-core = { path = "../../../electron-overlay-core" }
hudhook.workspace = true
tracing-subscriber.workspace = true
windows.workspace = true
