[package]
name = "hudhook-imgui-overlay-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
electron-overlay-transport = { path = "../../../../libs/electron-overlay-transport" }
hudhook.workspace = true
tracing-subscriber.workspace = true
windows.workspace = true
